version: "3.7"
services:
    app:
      build:
          args:
            user: alex
            uid: 1000
          context: ./
          dockerfile: ./docker-compose/php-fpm/Dockerfile
      image: web-front-docker
      container_name: web-front
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
          - ./:/var/www
      networks:
          - web-ui
    nginx:
      image: nginx:alpine
      container_name: web-front-nginx
      restart: unless-stopped
      ports:
          - 8010:80
      volumes:
          - ./:/var/www
          - ./docker-compose/nginx:/etc/nginx/conf.d
      networks:
          - web-ui
    #Mysl Service:
    mysql:
      image: mysql:5.7
      ports:
          - 3307:3306
      volumes:
          - /var/lib/mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: 3fsqdrifj6
          MYSQL_USER: alex
          MYSQL_PASSWORD: 3fsqdrifj6
          MYSQL_DATABASE: titila


networks:
  web-ui:
    driver: bridge